[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "quantlab"
version = "0.1.0"
description = "AI-powered crypto and financial research assistant"
requires-python = ">=3.11"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["src"]